# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: zos-spark/scala-notebook
    container_name: ${WORKBOOK_NAME}
    command: >
      bash -c "start-notebook.sh --port=${WORKBOOK_PORT} ${WORKBOOK_DEBUG}"
    network_mode: "host"
    environment:
      USE_HTTPS: "yes"
      PASSWORD: ${PASSWORD}
      SPARK_HOST_IP: ${WORKBOOK_IP}
    volumes:
      - "work:/home/jovyan/work"
volumes:
  work:
    external:
      name: ${WORKBOOK_VOLUME}
